resolver: lts-7.16

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
   git: https://github.com/BNFC/bnfc.git
   commit: 6160fe65516fa3af8dde1139c504653d45aba272
  subdirs:
  - source
  
# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- mtl-2.2.1
- alex-3.2.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
